### ISSUE TITLE
Implementaion of Cues in Event Master

### ISSUE THREAD

**Issue by mko1989** [bitfocus/companion-module-barco-eventmaster-xml#2]
**Describe the feature**
I'd like to be able to play cues created in Event Master Toolset. This is a new feature in versions 6.0 and above of Event Master Toolset.

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

Here are JSON commands for cues from the Event Master manual:

activateCue
• Definition:

This API provides the option to play/pause/stop a cue.
User can recall cue with id, serial number, or name.
• Request:
params: {"id": 1, "type": x}, "method":"activateCue", "id":"1234",
"jsonrpc":"2.0"}
◦ id – Index of the cue
◦ type – (Default is play). x" can be : 0 — Play. 0 is the default value for the type parameter. 1 —
Pause, 2 – Stop
params: {"cueName": "Cue1", "type": x}, "method":"activateCue", "id":"1234",
"jsonrpc":"2.0"}
params: {"cueSerialNo": 1.00, "type": x}, "method":"activateCue", "id":"1234",
"jsonrpc":"2.0"}
• Response:
response: null
success: (0=success, anything else is an error)
• Example:
{"params": {"id": 1}, "method":"activateCue", "id":"1234", "jsonrpc":"2.0"}
//Play – no parame or type 0
{"params": {"type": 1}, "method":"activateCue", "id":"1234", "jsonrpc":"2.0"}
//Pause – type 1
{"params": {"type": 2}, "method":"activateCue", "id":"1234", "jsonrpc":"2.0"}
//Stop – type 2
listCues
• Definition:

This API lists all the cues.
• Request:
params: {}, "method":"listCues", "id":"1234", "jsonrpc":"2.0"}
◦ id – Index of the input config.
• Response:
response: Array of cue objects.
success: (0=success, anything else is an error)
• Example:
{"params": {}, "method":"listCues", "id":"1234", "jsonrpc":"2.0"}

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.
Well, I'd really like to use this functionality because it works great for me and using it with a press of a button on streamdeck would be awesome.

**Comment by JeffreyDavidsz** [comment]
Hey WIlliam, I've added the 2 API functions in your stuff. Pull request ready. So how does this work? You'll merge and then we need an update in the barco module? After thats finished, create the newly added  functions in the module?

**Comment by willosof** [comment]
I think this works now? Closing ticket.

**Comment by JeffreyDavidsz** [comment]
It does
