### ISSUE TITLE
Feature Request - Expanded Eventmaster XML support

### ISSUE THREAD

**Issue by bmacrow** [bitfocus/companion-module-barco-eventmaster-xml#4]
**Describe the feature**
Would be great to see Eventmaster support extended from just Preset/PGM recall to the full JSON/XML support, there are loads of things you can do through JSON/XML control of EM, from freezing sources right through to changing multiviewer configs and as a regular EM user it would be a gamechanger.

If that's too much (for now), just being able to send custom JSON/XML commands to EM through companion would be great so I can do everything by attaching custom JSON/XML strings to streamdeck buttons.

**Is this platform dependent (windows, mac, ..)?**
Platform independent

**If documentation is required to implement, do you know where to find it?**
A user on the octopus FB group has added a method for getting the XML commands out of EM so you can find out which command strings are required; that doc is here: [https://www.facebook.com/download/871927482997198/Bacro%20e2%20XML%20Octopus%20commands.pdf?hash=Acqa61PqZxEUiRjt](url)

and the Barco documentation also provides some of the commands required [https://www.barco.com/services/website/en/TdeFiles/Download?FileNumber=R5905948&TdeType=1&Revision=09&ShowDownloadPage=False](url)

**Usecases**
To get the best out of Eventmaster and be able to program and/or run shows quickly, an external control surface is needed, but Barco's surfaces are very expensive (prohibitively so for freelancers). To be able to use streamdeck as a smaller version of the Barco control surface, with the custom buttons and commands that it allows, would be a game changer for EventMaster ops everywhere!

**Comment by JeffreyDavidsz** [comment]
general xml supported
